# SPDX-License-Identifier: GPL-2.0-only

ifeq ($(CONFIG_CRYPTO_DEV_NUVOTON_MA35D1),y)
	obj-y += ma35d1-crypto.o
	obj-y += ma35d1-aes.o
	obj-y += ma35d1-prng.o
	obj-y += ma35d1-sha.o
	obj-y += ma35d1-ecc.o
	obj-y += ma35d1-rsa.o
	obj-y += ma35d1-crypto-optee.o
	obj-y += ma35d1-aes-optee.o
	obj-y += ma35d1-sha-optee.o
	obj-y += ma35d1-ecc-optee.o
	obj-y += ma35d1-rsa-optee.o
endif
